# Generated by Django 4.2.1 on 2023-06-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='is_Estudiante',
            field=models.BooleanField(default=False, verbose_name='Estudiante'),
        ),
    ]
